[package]
name = "chessai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
rand = "0.8.5"
byteorder = "1.4.3"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
